name: Dime
description: A financial features application for younger people.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  geoflutterfire: ^2.0.3+5
  grouped_buttons:
  xlive_switch:
  flutter_search_panel:
  fancy_on_boarding:
  page_transition:
  flutter_test:
    sdk: flutter
  firebase_auth: ^0.11.1+12
  cloud_firestore:
  firebase_storage:
  shared_preferences: ^0.5.1+2
  modal_progress_hud: ^0.1.3
  flutter_facebook_login:
  timeago: ^2.0.18
  image_picker: ^0.6.1+3
  queries: ^0.1.12
  http: ^0.12.0+2
  flutter_webview_plugin: ^0.3.7
  location:
  charts_flutter:
  flutter_screenutil: ^0.5.2
  flutter_vector_icons:
  permission_handler: ^3.1.0
  contacts_service: ^0.2.8
  sticky_infinite_list:
  rubber:
  flushbar: ^1.8.2
  flutter_tagging: ^1.1.0
  carousel_slider: ^1.3.0
  google_sign_in:
  url_launcher: ^5.1.2
  share:
  esys_flutter_share:
  wc_flutter_share:
  flutter_fluid_slider:
  image: ^2.0.7
  auto_size_text:
  intro_views_flutter:
    git: git://github.com/aagarwal1012/IntroViews-Flutter
  latlong: ^0.6.1
  flutter_spinkit: ^3.1.0
  google_maps_flutter:
  firebase_messaging:
  cached_network_image: ^1.1.1
  path_provider: ^1.2.0
  image_cropper: ^1.0.2
  geolocator: '^5.1.1'
  #geolocation:
    #git:
      #url: https://github.com/shehabic/geolocation
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  image_path: "assets/img/GroupDimeTransparent.png"
  android: true
  ios: false





# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login_logo.png
    - assets/namrapatel.png
    - assets/dimelogo.png
    - assets/dimelogo1.png
    - assets/dimewhite.png
    - assets/shehabsalem.jpeg
    - assets/taher.jpeg
    - assets/defaultprofile.png
    - assets/dhruvpatel.jpeg
    - assets/groupselfie.png
    - assets/friendsDrawing.png
    - assets/improvingDrawing.png
    - assets/nearbyUI.png
    - assets/mapsUI.png
    - assets/profPageUI.png
    - assets/socialAndProfCard.png
    - assets/white.png
    - assets/pplNearbyUI.png
    - assets/undraw_peoplearoundyou.png
    - assets/undraw_messages.png
    - assets/feeds.png
    - assets/DimeLogoBlue.png
    - assets/Dime3Colors.png
    - assets/GroupDimeTransparent.png
    - assets/darkpeoplearoundyou.png
    - assets/clickablecards.png
    - assets/darkdirectory.png
    - assets/vsco.png


  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/Futura-book.ttf
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/proxima-nova.ttf    
